# Generated by Django 3.1.12 on 2025-10-02 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='faculte',
            field=models.ForeignKey(blank=True, help_text="Faculté d'appartenance", null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.faculte'),
        ),
    ]
