# Generated by Django 3.1.12 on 2025-10-01 17:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='matricule',
            field=models.CharField(help_text='Matricule unique (ex: UOM2025-001)', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Le matricule doit être au format UOM2025-001', regex='^UOM\\d{4}-\\d{3}$')]),
        ),
    ]
