# Generated by Django 3.1.12 on 2025-10-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20251001_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='photo',
            field=models.ImageField(blank=True, help_text='Photo de profil', null=True, upload_to='profiles/students/%Y/%m/'),
        ),
    ]
