# Generated by Django 3.1.12 on 2025-10-17 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_teacherprofile_faculte'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraisAcademique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_academique', models.CharField(help_text='Année académique (ex: 2023-2024)', max_length=20)),
                ('montant_total', models.DecimalField(decimal_places=2, help_text='Montant total des frais en USD', max_digits=10)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, help_text='Montant déjà payé en USD', max_digits=10)),
                ('date_paiement', models.DateTimeField(blank=True, help_text='Date du dernier paiement', null=True)),
                ('mode_paiement', models.CharField(blank=True, choices=[('espece', 'Espèces'), ('carte', 'Carte bancaire'), ('virement', 'Virement bancaire'), ('mobile', 'Mobile money')], help_text='Mode de paiement', max_length=50)),
                ('reference_paiement', models.CharField(blank=True, help_text='Référence du paiement', max_length=100)),
                ('statut', models.CharField(choices=[('non_paye', 'Non payé'), ('partiel', 'Paiement partiel'), ('complet', 'Payé')], default='non_paye', help_text='Statut du paiement', max_length=20)),
                ('remarques', models.TextField(blank=True, help_text='Remarques ou notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etudiant', models.ForeignKey(help_text='Étudiant concerné', limit_choices_to={'user_type': 'etudiant'}, on_delete=django.db.models.deletion.CASCADE, related_name='frais_academiques', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Frais Académique',
                'verbose_name_plural': 'Frais Académiques',
                'ordering': ['-annee_academique', 'etudiant'],
                'unique_together': {('etudiant', 'annee_academique')},
            },
        ),
    ]
