# Generated by Django 3.1.12 on 2025-10-01 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Travail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Titre du travail', max_length=200)),
                ('description', models.TextField(help_text='Description du travail')),
                ('consignes', models.TextField(help_text='Consignes pour les étudiants')),
                ('type_travail', models.CharField(choices=[('tp', 'Travaux Pratiques'), ('td', 'Travaux Dirigés'), ('projet', 'Projet'), ('examen', 'Examen'), ('autre', 'Autre')], default='tp', max_length=20)),
                ('niveau', models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2')], max_length=5)),
                ('filiere', models.CharField(help_text='Filière concernée', max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_publication', models.DateTimeField(blank=True, help_text='Date de publication', null=True)),
                ('date_limite_remise', models.DateTimeField(help_text='Date limite de remise')),
                ('date_limite_correction', models.DateTimeField(blank=True, help_text='Date limite de correction', null=True)),
                ('note_maximale', models.DecimalField(decimal_places=2, default=20.0, help_text='Note maximale', max_digits=5)),
                ('coefficient', models.DecimalField(decimal_places=2, default=1.0, help_text='Coefficient', max_digits=3)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('ferme', 'Fermé'), ('corrige', 'Corrigé')], default='brouillon', max_length=20)),
                ('is_visible_etudiants', models.BooleanField(default=True, help_text='Visible pour les étudiants')),
                ('fichier_consignes', models.FileField(blank=True, help_text='Fichier de consignes (optionnel)', null=True, upload_to='travaux/consignes/%Y/%m/')),
                ('enseignant', models.ForeignKey(limit_choices_to={'user_type': 'enseignant'}, on_delete=django.db.models.deletion.CASCADE, related_name='travaux_enseignant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Travail',
                'verbose_name_plural': 'Travaux',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='RemiseTravail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_principal', models.FileField(help_text='Fichier principal du travail', upload_to='travaux/remises/%Y/%m/')),
                ('fichiers_supplementaires', models.FileField(blank=True, help_text='Fichiers supplémentaires (optionnel)', null=True, upload_to='travaux/remises/%Y/%m/')),
                ('commentaire_etudiant', models.TextField(blank=True, help_text="Commentaire de l'étudiant")),
                ('commentaire_enseignant', models.TextField(blank=True, help_text="Commentaire de l'enseignant")),
                ('date_remise', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('remis', 'Remis'), ('en_cours_correction', 'En cours de correction'), ('corrige', 'Corrigé'), ('note_finalisee', 'Note finalisée')], default='remis', max_length=30)),
                ('note', models.DecimalField(blank=True, decimal_places=2, help_text='Note obtenue', max_digits=5, null=True)),
                ('date_correction', models.DateTimeField(blank=True, help_text='Date de correction', null=True)),
                ('score_plagiat', models.DecimalField(blank=True, decimal_places=2, help_text='Score de similarité (0-100%)', max_digits=5, null=True)),
                ('rapport_plagiat', models.TextField(blank=True, help_text='Rapport de détection de plagiat')),
                ('etudiant', models.ForeignKey(limit_choices_to={'user_type': 'etudiant'}, on_delete=django.db.models.deletion.CASCADE, related_name='remises_etudiant', to=settings.AUTH_USER_MODEL)),
                ('travail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remises', to='travaux.travail')),
            ],
            options={
                'verbose_name': 'Remise de travail',
                'verbose_name_plural': 'Remises de travaux',
                'ordering': ['-date_remise'],
                'unique_together': {('etudiant', 'travail')},
            },
        ),
    ]
