# Generated by Django 3.1.12 on 2025-10-09 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0003_cours_credits'),
        ('travaux', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travail',
            name='cours',
            field=models.ForeignKey(blank=True, help_text='Cours auquel ce travail appartient', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='travaux', to='cours.cours'),
        ),
    ]
