# Generated by Django 3.1.12 on 2025-10-01 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Titre du cours', max_length=200)),
                ('code', models.CharField(help_text='Code du cours (ex: INFO101)', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description du cours')),
                ('type_cours', models.CharField(choices=[('cours', 'Cours Magistral'), ('tp', 'Travaux Pratiques'), ('td', 'Travaux Dirigés'), ('projet', 'Projet')], default='cours', max_length=20)),
                ('niveau', models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2')], max_length=5)),
                ('filiere', models.CharField(help_text='Filière concernée', max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_debut', models.DateField(help_text='Date de début du cours')),
                ('date_fin', models.DateField(help_text='Date de fin du cours')),
                ('is_actif', models.BooleanField(default=True, help_text='Cours actif')),
                ('is_visible_etudiants', models.BooleanField(default=True, help_text='Visible pour les étudiants')),
                ('enseignant', models.ForeignKey(limit_choices_to={'user_type': 'enseignant'}, on_delete=django.db.models.deletion.CASCADE, related_name='cours_enseignant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='SupportCours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Titre du support', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description du support')),
                ('type_support', models.CharField(choices=[('cours', 'Support de cours'), ('tp', 'TP'), ('td', 'TD'), ('corrige', 'Corrigé'), ('autre', 'Autre')], default='cours', max_length=20)),
                ('fichier', models.FileField(help_text='Fichier du support', upload_to='cours/supports/%Y/%m/')),
                ('taille_fichier', models.PositiveIntegerField(blank=True, help_text='Taille en octets', null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now, help_text='Date de publication')),
                ('is_public', models.BooleanField(default=True, help_text='Visible pour les étudiants')),
                ('ordre_affichage', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage")),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supports', to='cours.cours')),
                ('enseignant', models.ForeignKey(limit_choices_to={'user_type': 'enseignant'}, on_delete=django.db.models.deletion.CASCADE, related_name='supports_enseignant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Support de cours',
                'verbose_name_plural': 'Supports de cours',
                'ordering': ['ordre_affichage', '-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='InscriptionCours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, help_text="Date de validation par l'enseignant", null=True)),
                ('is_valide', models.BooleanField(default=False, help_text='Inscription validée')),
                ('is_actif', models.BooleanField(default=True, help_text='Inscription active')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='cours.cours')),
                ('etudiant', models.ForeignKey(limit_choices_to={'user_type': 'etudiant'}, on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_cours', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscription au cours',
                'verbose_name_plural': 'Inscriptions aux cours',
                'ordering': ['-date_inscription'],
                'unique_together': {('etudiant', 'cours')},
            },
        ),
    ]
