# Generated by Django 3.1.12 on 2025-10-02 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_teacherprofile_faculte'),
        ('cours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='faculte',
            field=models.ForeignKey(blank=True, help_text='Faculté du cours', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cours_faculte', to='users.faculte'),
        ),
        migrations.AddField(
            model_name='cours',
            name='promotion',
            field=models.ForeignKey(blank=True, help_text='Promotion concernée', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cours_promotion', to='users.promotion'),
        ),
    ]
