# Generated by Django 3.1.12 on 2025-10-09 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0002_auto_20251002_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='credits',
            field=models.PositiveIntegerField(default=3, help_text='Nombre de crédits ECTS'),
        ),
    ]
