# Generated by Django 3.1.12 on 2025-10-10 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memoire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Titre du mémoire', max_length=500)),
                ('description', models.TextField(help_text='Description détaillée du sujet')),
                ('objectifs', models.TextField(help_text='Objectifs du mémoire')),
                ('domaine', models.CharField(choices=[('informatique', 'Informatique'), ('genie_civil', 'Génie Civil'), ('gestion', 'Gestion'), ('droit', 'Droit'), ('sciences', 'Sciences'), ('lettres', 'Lettres'), ('economie', 'Économie'), ('autre', 'Autre')], help_text="Domaine d'étude", max_length=50)),
                ('domaine_autre', models.CharField(blank=True, help_text="Précisez si 'Autre'", max_length=200, null=True)),
                ('fichier_memoire', models.FileField(blank=True, help_text='Fichier PDF du mémoire final', null=True, upload_to='memoires/documents/%Y/%m/')),
                ('date_soumission_sujet', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_depot_final', models.DateTimeField(blank=True, null=True)),
                ('date_certification', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumis', 'Soumis pour validation'), ('valide', 'Validé'), ('refuse', 'Refusé'), ('en_cours', 'En cours de rédaction'), ('termine', 'Terminé'), ('certifie', 'Certifié')], default='brouillon', max_length=20)),
                ('commentaire_etudiant', models.TextField(blank=True, help_text="Commentaire de l'étudiant")),
                ('commentaire_admin', models.TextField(blank=True, help_text="Commentaire de l'administration")),
                ('motif_refus', models.TextField(blank=True, help_text='Motif de refus du sujet')),
                ('score_plagiat', models.DecimalField(blank=True, decimal_places=2, help_text='Score de plagiat (0-100%)', max_digits=5, null=True)),
                ('rapport_plagiat', models.TextField(blank=True, help_text='Rapport anti-plagiat')),
                ('plagiat_verifie', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('directeur', models.ForeignKey(blank=True, help_text='Directeur du mémoire', limit_choices_to={'user_type': 'enseignant'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memoires_directeur', to=settings.AUTH_USER_MODEL)),
                ('encadreur', models.ForeignKey(blank=True, help_text='Encadreur du mémoire', limit_choices_to={'user_type': 'enseignant'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memoires_encadreur', to=settings.AUTH_USER_MODEL)),
                ('etudiant', models.ForeignKey(limit_choices_to={'user_type': 'etudiant'}, on_delete=django.db.models.deletion.CASCADE, related_name='memoires_etudiant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mémoire',
                'verbose_name_plural': 'Mémoires',
                'ordering': ['-date_soumission_sujet'],
            },
        ),
        migrations.CreateModel(
            name='CertificatMemoire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_certificat', models.CharField(max_length=50, unique=True)),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
                ('annee_academique', models.CharField(help_text='Année académique (ex: 2024-2025)', max_length=9)),
                ('memoire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificat', to='memoires.memoire')),
            ],
            options={
                'verbose_name': 'Certificat de Mémoire',
                'verbose_name_plural': 'Certificats de Mémoire',
                'ordering': ['-date_emission'],
            },
        ),
    ]
