# Generated by Django 3.1.12 on 2025-10-01 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Code de l'UE (ex: INFO101)", max_length=20, unique=True)),
                ('nom', models.CharField(help_text="Nom de l'UE", max_length=200)),
                ('description', models.TextField(blank=True, help_text="Description de l'UE")),
                ('niveau', models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2')], max_length=5)),
                ('semestre', models.CharField(choices=[('S1', 'Semestre 1'), ('S2', 'Semestre 2'), ('S3', 'Semestre 3'), ('S4', 'Semestre 4'), ('S5', 'Semestre 5'), ('S6', 'Semestre 6'), ('S7', 'Semestre 7'), ('S8', 'Semestre 8'), ('S9', 'Semestre 9'), ('S10', 'Semestre 10')], max_length=5)),
                ('filiere', models.CharField(help_text='Filière concernée', max_length=100)),
                ('credits', models.PositiveIntegerField(default=3, help_text='Nombre de crédits ECTS')),
                ('coefficient', models.DecimalField(decimal_places=2, default=1.0, help_text='Coefficient', max_digits=3)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_debut', models.DateField(help_text="Date de début de l'UE")),
                ('date_fin', models.DateField(help_text="Date de fin de l'UE")),
                ('is_actif', models.BooleanField(default=True, help_text='UE active')),
                ('is_visible_etudiants', models.BooleanField(default=True, help_text='Visible pour les étudiants')),
                ('enseignant_responsable', models.ForeignKey(limit_choices_to={'user_type': 'enseignant'}, on_delete=django.db.models.deletion.CASCADE, related_name='ues_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Unité d'Enseignement",
                'verbose_name_plural': "Unités d'Enseignement",
                'ordering': ['niveau', 'semestre', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_note', models.CharField(choices=[('tp', 'Travaux Pratiques'), ('td', 'Travaux Dirigés'), ('examen', 'Examen'), ('projet', 'Projet'), ('participation', 'Participation'), ('autre', 'Autre')], default='examen', max_length=20)),
                ('titre', models.CharField(help_text="Titre de l'évaluation", max_length=200)),
                ('description', models.TextField(blank=True, help_text="Description de l'évaluation")),
                ('note_obtenue', models.DecimalField(decimal_places=2, help_text='Note obtenue', max_digits=5)),
                ('note_maximale', models.DecimalField(decimal_places=2, default=20.0, help_text='Note maximale', max_digits=5)),
                ('coefficient', models.DecimalField(decimal_places=2, default=1.0, help_text='Coefficient de la note', max_digits=3)),
                ('date_evaluation', models.DateField(help_text="Date de l'évaluation")),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now, help_text='Date de publication de la note')),
                ('commentaire', models.TextField(blank=True, help_text="Commentaire de l'enseignant")),
                ('is_publie', models.BooleanField(default=True, help_text="Note publiée (visible pour l'étudiant)")),
                ('is_definitive', models.BooleanField(default=False, help_text='Note définitive')),
                ('enseignant', models.ForeignKey(limit_choices_to={'user_type': 'enseignant'}, on_delete=django.db.models.deletion.CASCADE, related_name='notes_enseignant', to=settings.AUTH_USER_MODEL)),
                ('etudiant', models.ForeignKey(limit_choices_to={'user_type': 'etudiant'}, on_delete=django.db.models.deletion.CASCADE, related_name='notes_etudiant', to=settings.AUTH_USER_MODEL)),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='resultats.ue')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='InscriptionUE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, help_text='Date de validation', null=True)),
                ('is_valide', models.BooleanField(default=False, help_text='Inscription validée')),
                ('is_actif', models.BooleanField(default=True, help_text='Inscription active')),
                ('etudiant', models.ForeignKey(limit_choices_to={'user_type': 'etudiant'}, on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_ue', to=settings.AUTH_USER_MODEL)),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='resultats.ue')),
            ],
            options={
                'verbose_name': 'Inscription UE',
                'verbose_name_plural': 'Inscriptions UE',
                'ordering': ['-date_inscription'],
                'unique_together': {('etudiant', 'ue')},
            },
        ),
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_academique', models.CharField(help_text='Année académique (ex: 2024-2025)', max_length=9)),
                ('semestre', models.CharField(choices=[('S1', 'Semestre 1'), ('S2', 'Semestre 2'), ('S3', 'Semestre 3'), ('S4', 'Semestre 4'), ('S5', 'Semestre 5'), ('S6', 'Semestre 6'), ('S7', 'Semestre 7'), ('S8', 'Semestre 8'), ('S9', 'Semestre 9'), ('S10', 'Semestre 10')], max_length=5)),
                ('moyenne_semestre', models.DecimalField(blank=True, decimal_places=2, help_text='Moyenne du semestre', max_digits=5, null=True)),
                ('moyenne_annee', models.DecimalField(blank=True, decimal_places=2, help_text="Moyenne de l'année", max_digits=5, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now, help_text='Date de publication')),
                ('is_publie', models.BooleanField(default=True, help_text='Bulletin publié')),
                ('is_definitif', models.BooleanField(default=False, help_text='Bulletin définitif')),
                ('etudiant', models.ForeignKey(limit_choices_to={'user_type': 'etudiant'}, on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bulletin',
                'verbose_name_plural': 'Bulletins',
                'ordering': ['-date_creation'],
                'unique_together': {('etudiant', 'annee_academique', 'semestre')},
            },
        ),
    ]
